include!("tests/part_00.rs");
include!("tests/part_01.rs");
include!("tests/part_02.rs");
include!("tests/part_03.rs");
include!("tests/part_04.rs");
include!("tests/part_05.rs");
include!("tests/provider_streaming.rs");
include!("tests/streaming_replay.rs");
include!("tests/streaming_cancellation.rs");
include!("tests/part_07.rs");
mod otel_span_tests;
