include!("tests/support.rs");
include!("tests/basic_loop.rs");
include!("tests/budget_context_errors.rs");
include!("tests/clock_and_replay.rs");
include!("tests/replay_divergence.rs");
include!("tests/replay_frontier.rs");
include!("tests/turn_runtime.rs");
include!("tests/parallel_tool_runtime.rs");
include!("tests/tool_cancellation.rs");
include!("tests/provider_streaming.rs");
include!("tests/streaming_replay.rs");
include!("tests/streaming_cancellation.rs");
include!("tests/hitl.rs");
mod otel_span_tests;
